server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanmal/Bootcamp-ConfigServer
          default-label: main
          search-paths:
          - '*reto'